pub const OpCodeName = enum {
    SetIndex,
    SetRegister,
    DrawSprite,
    CallFunction,
    Return,
    Jump,
    SetDelayTimer,
    StoreBCD,
    LoadIntoRegisters,
    SetIndexToSprite,
    Add,
    Assign,
    Equal,
    NotEqual,
    Random,
    Nop,
    Count
};

pub const OpCode = union(OpCodeName) {
    SetIndex: u16,
    SetRegister: struct { register_name: u8, value: u8 },
    DrawSprite: struct { x: u8, y: u8, height: u8},
    CallFunction: u16,
    Return: void,
    Jump: u16,
    SetDelayTimer: u8,
    StoreBCD: u8,
    LoadIntoRegisters: u8,
    SetIndexToSprite: u8,
    Add: struct { register_name: u8, value: u8 },
    Assign: struct { register_destination: u8, register_source: u8 },
    Equal: struct { register_name: u8, value: u8 },
    NotEqual: struct { register_name: u8, value: u8 },
    Random: struct { register_name: u8, bitwise_and_value: u8 },
    Nop: void,
    Count: void,
};